# Built with Jekyll 3.2.0
#
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: none

# Set encoding to UTF-8
# encoding: utf-8

# Markdown specs
markdown: kramdown

# collections:
#   texts:
#     output: true

# Rouge is the default highlighter in Jekyll 3 and above
highlighter: rouge

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  input:          GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Setup
title:               Le.
tagline:             'A weird dude'
description:         "I am not afraid of dying. I'm afraid I haven't been alive enough - Mr_Nobody"
url:                 https://crushcoding.com
baseurl:             # '/ed'

# About/contact
author:
  name:              Le Dinh-Tuyen
  url:               https://github.com/tuyenld
  email:             tuyenld.work@gmail.com

# Custom vars
version:             0.0.5

# Exclude optional folder
exclude: 
  - vendor
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - ed..gemspec 

# Gems
plugins: ['jekyll/scholar']

# Scholar
scholar:
  style: modern-language-association
  locale: en

  sort_by: none
  order: ascending

  group_by: none
  group_order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: "{{reference}}"
  relative: "bibliography.html"

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: false

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"

## => Paginate: number of recent post on homepage
max_recent_posts: 6

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"

google_custom_search_engine_id: 014783372275656596289:xyeevhsbdw8 # Google Custom Search Engine ID
cloudinaryurl : "https://res.cloudinary.com/crushcoding/image/upload/q_auto,f_auto/"

# Add `comments: true` to the post’s YAML Front Matter you want to show comment
utterance:
  repo:  "tuyenld/tuyenld.github.io" # Choose the repository utterances will connect to. eg: owner/repo
  issue-term: "pathname"   # Choose the mapping between blog posts and GitHub issues. 
  theme: "github-light" # Choose an Utterances theme that matches your blog. 'github-light' is default

  ## Optional
  label:  blog-comments # Choose the label that will be assigned to issues created by Utterances.

permalink: /:categories/:title
# Google services
google_analytics: UA-133437467-1

# For development only
host: 0.0.0.0
port: 4000