title: Tuyen's hard drive
description: Where is my memory
baseurl: ""
url: "https://tuyenld.github.io"
repository: tuyenld/tuyenld.github.io
paginate: 28

banner: "/assets/res/dolphin.png" # site banner (load when someone share your page url)
favicon: "/assets/res/dolphin.png" # site's favicon (icon left side of your page)

# MatJek specific configurations
user: 
  name: "Dinh-Tuyen Le"
  email: "tuyenld.work@gmail.com"
  website: "deeplearningera.com"
  avatar: "/assets/res/brain.png"
  github: "tuyenld"
# google_tracking_id: ""
# google_site_verification: ""
# disqus_shortname: this-site

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title


plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed

  future: true

# --------------------------------------------------------
# tuyen added
# --------------------------------------------------------
ext:
  fonts:
    # inter: "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap" 
    # dacingScript: "https://fonts.googleapis.com/css?family=Dancing+Script:400,700&amp;subset=vietnamese" 
    # materialIcons: "https://fonts.googleapis.com/icon?family=Material+Icons"
  jquery: 
    src: # "//code.jquery.com/jquery-3.5.1.min.js"
    integrity: # "sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="

  materialize:
    js: # "//cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/js/materialize.min.js"
    css: # "//cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/css/materialize.min.css"

googleSiteVerification:

# For development only
host: 0.0.0.0
port: 4000

utterance:
  repo:  "tuyenld/tuyenld.github.io" # Choose the repository utterances will connect to. eg: owner/repo
  issue-term: "pathname"   # Choose the mapping between blog posts and GitHub issues. 
  theme: "github-light" # Choose an Utterances theme that matches your blog. 'github-light' is default
  label:  blog-comments # (Optional) Choose the label that will be assigned to issues created by Utterances.

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"

# Add this fontmater to the post: {{ site.cloudinaryurl }}
cloudinaryurl : "https://res.cloudinary.com/crushcoding/image/upload/q_auto,f_auto/"
# or cloudimage.io 25 GB of Monthly CDN Traffic
# no resize, no filter from sample.li/flat_600_400.jpg
# https://demo.cloudimg.io/cdn/n/n/sample.li/flat_600_400.jpg
